# Generated by Django 5.2.7 on 2025-10-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(help_text='Breve resumen del proyecto', max_length=500, verbose_name='Descripción Corta')),
                ('category', models.CharField(choices=[('web', 'Aplicación Web'), ('mobile', 'Aplicación Móvil'), ('desktop', 'Aplicación de Escritorio'), ('api', 'API REST'), ('bot', 'Bot'), ('script', 'Script/Herramienta'), ('otro', 'Otro')], default='web', max_length=20, verbose_name='Categoría')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('paused', 'Pausado'), ('archived', 'Archivado')], default='completed', max_length=20, verbose_name='Estado')),
                ('technologies', models.CharField(help_text='Separa con comas: Python, Django, PostgreSQL', max_length=500, verbose_name='Tecnologías')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Imagen del Proyecto')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='URL de GitHub')),
                ('live_url', models.URLField(blank=True, null=True, verbose_name='URL en Vivo')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado en Portafolio')),
                ('order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-featured', '-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Habilidad')),
                ('category', models.CharField(help_text='Ej: Lenguaje, Framework, Base de Datos', max_length=50, verbose_name='Categoría')),
                ('level', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='intermediate', max_length=20, verbose_name='Nivel')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Ícono (Font Awesome)')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['category', 'order'],
            },
        ),
    ]
