# Generated by Django 5.2.7 on 2025-10-21 21:02

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Recibido en')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Leído')),
                ('responded', models.BooleanField(default=False, verbose_name='Respondido')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tu nombre y apellidos', max_length=200, verbose_name='Nombre completo')),
                ('title', models.CharField(help_text='Ej: Desarrollador Full Stack, Ingeniero de Software', max_length=200, verbose_name='Título profesional')),
                ('bio', models.TextField(help_text='Descripción detallada sobre ti y tu experiencia', verbose_name='Biografía')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, help_text='Formato: +34 666281793', max_length=20, verbose_name='Teléfono')),
                ('location', models.CharField(help_text='Ciudad, País', max_length=200, verbose_name='Ubicación')),
                ('age', models.IntegerField(validators=[projects.models.validate_age], verbose_name='Edad')),
                ('profile_image', models.ImageField(blank=True, help_text='Imagen JPG o PNG, máximo 5MB', null=True, upload_to='profile/%Y/%m/', verbose_name='Foto de perfil')),
                ('cv_file', models.FileField(blank=True, help_text='Documento PDF con tu CV', null=True, upload_to='cv/%Y/', verbose_name='Currículum (PDF)')),
                ('github_url', models.URLField(blank=True, help_text='URL completa de tu perfil', verbose_name='Perfil GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Perfil LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Perfil Twitter')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Perfil Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Perfil profesional',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Detalles sobre tu experiencia con esta habilidad', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Aplicación Web'), ('mobile', 'Aplicación Móvil'), ('desktop', 'Aplicación de Escritorio'), ('api', 'API REST'), ('bot', 'Bot'), ('script', 'Script/Herramienta'), ('otro', 'Otro')], db_index=True, default='web', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Explicación completa del proyecto, objetivos y resultados', verbose_name='Descripción detallada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Aparecerá en la página de inicio', verbose_name='Destacado en inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Repositorio del proyecto', null=True, verbose_name='URL de GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Captura de pantalla o thumbnail', null=True, upload_to='projects/%Y/%m/', verbose_name='Imagen del proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Demo o sitio desplegado', null=True, verbose_name='URL en vivo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(help_text='Resumen en una línea para listados', max_length=500, verbose_name='Descripción corta'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En Progreso'), ('paused', 'Pausado'), ('archived', 'Archivado')], db_index=True, default='completed', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Separa con comas: Python, Django, PostgreSQL', max_length=500, verbose_name='Tecnologías utilizadas'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Título del proyecto'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('language', 'Lenguaje de Programación'), ('framework', 'Framework'), ('database', 'Base de Datos'), ('tool', 'Herramienta'), ('platform', 'Plataforma'), ('other', 'Otro')], db_index=True, help_text='Tipo de habilidad', max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text='Ej: fab fa-python, fas fa-database', max_length=100, verbose_name='Clase Font Awesome'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado'), ('expert', 'Experto')], default='intermediate', max_length=20, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Habilidad'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden de visualización'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'category')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-featured', '-start_date'], name='projects_pr_feature_a673d4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', '-start_date'], name='projects_pr_categor_d811f6_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'order'], name='projects_sk_categor_36ebe6_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created_at', 'read'], name='projects_co_created_fb175f_idx'),
        ),
    ]
